### PR TITLE
Increment major version numbers (and thus filenames) of things from 6M62

### PR DESCRIPTION
**Pull request by zedlopez**
increment major version number of extensions from 6M62 that had had D/DDDDDD style version numbers.

Remove execute permission from two extensions that strangely had it.

Incidentally added newlines at the ends of extensions that didn't end with one.

### CODE REVIEW

**Comment by zedlopez** [comment]
never mind. I need to smoketest these to see if the incrementing broke something else.

**Comment by zedlopez** [comment]
I'm very surprised, but the smoketester found no errors from the version changes.

**Comment by curiousdannii** [comment]
Would 1.200000 be better? If it's not actually a major version update...

**Comment by zedlopez** [comment]
I figure they weren't really semantic version numbers in 6M62-land and that the initial assignment of the lower version number was an error with under a day's worth of history, so I feel really okay with incrementing them.

Also, I really don't feel like fixing them all again.

do you feel strongly about this?

**Comment by curiousdannii** [comment]
No, not strongly.

**Comment by zedlopez** [comment]
or, we could appeal to Graham to have inform officially interpret 1/220522 as 1.1.220522, in which case the existing files work as is.

I can't say that I like the odds, though.

**Comment by zedlopez** [comment]
what the heck, I'm trying it. [I7-2130](https://inform7.atlassian.net/browse/I7-2130)

**Comment by zedlopez** [comment]
What is best in life, programmer-Conan?

To see your errors fixed by getting someone to revise the specification of correct behavior.

https://github.com/ganelson/inform/commit/3f3f1506f7a204d6f3567056c7142ff2c2973f5c

**Pull request closed without merging**
