### PR TITLE
Updated Jesse McGrew's Dynamic Objects to version 8

### PR DESCRIPTION
**Pull request by tunesmith**
I noticed that Dynamic Objects was updated elsewhere, so I figured it could be added here too?  kerkeruip requires this version.  This is my first attempt at a pull request so let me know if I'm screwing anything up.

### CODE REVIEW

**Comment by curiousdannii** [comment]
I'll give you direct access to the repo.

**Comment by tunesmith** [comment]
Thanks!  Is it also appropriate to add in other extensions by other authors, and bump versions of extensions if we notice problems?  For instance, "Questions" is out there and I'd like to add it and also remove a space from the title because it otherwise causes a hard-to-track-down bug in the Inform IDE.

**Comment by curiousdannii** [comment]
In general we've only been adding the extensions of others when we update them. There's no point just copying everything from the Inform 7 site. Adding them to fix bugs like that is good though!

**Comment by mciul** [comment]
I could have sworn we'd done this update already. Maybe this is the source of that crash I was having... wouldn't that be nice!

**Pull request merged**
