### PR TITLE
Version 6: minor edit

### PR DESCRIPTION
**Pull request by brirush84**
This version changes 'carried' to 'enclosed' in the inventory rule to fix a problem where player's clothing would disappear if they weren't holding anything.

Please ensure that you have followed these steps to make a pull request for 10.1 or 9.3 (6M62):

- [ ] This extension is stable and production-ready
  - Please also check that your extension only depends on other stable extensions which are supported for the target Inform 7 release. An extension which depends on extensions which are not stable cannot be accepted.
- [ ] This extension has a valid version number:
  - For 10.1: use [semantic versioning](https://semver.org/): `MAJOR.MINOR.PATCH`, ex: `2.1.0`. This means that the major version number must be incremented when and only when you make a change that is not backwards compatible.
  - For 9.3: use Inform's date based version number: `MAJOR/DATE`, ex: `2/220517`.
- [ ] This extension has the correct file name:
  - For 10.1: put the major version number at the end of the file name, ex: `Extension Name-v1.i7x`
  - For 9.3: do not include the version number, and the file name must match the extension's name as defined in the file exactly, ex:
    - File name: `Extension Name.i7x`
    - Extension begins: `Version 1/220517 of Extension Name by Author Name begins here.`
- [ ] This extension has documentation
- [ ] The correct branch (10.1 or 9.3) has been selected for this pull request

### CODE REVIEW

**Comment by curiousdannii** [comment]
I'll merge this, but note that most people do seem to use the 9.3 or 10.1 branches now.

**Comment by brirush84** [comment]
I'm not sure what that means; should I be making my updates to a different repo, or just downloading Inform 10 and compiling it on that before uploading?

**Comment by curiousdannii** [comment]
When you make a pull request you can select which branch you want it to go towards. There are a few differences for how version numbers are to be handled too, which the guidelines above explain.

**Comment by brirush84** [comment]
Oh, that makes sense. I actually didn't see those checkboxes when I submitted! I had tried to make it version 5.1, but it didn't compile on my Inform (I haven't updated it in years). Thanks for explaining it!

**Pull request merged**
