### PR TITLE
Include some how-to readme info

### PR DESCRIPTION
**Pull request by uecasm**
RFC.  What do you think of adding these FAQs?

### CODE REVIEW

**Comment by curiousdannii** [comment]
Great idea!

However, rather than suggesting `git`, what about explaining where to unzip the zip instead? https://github.com/i7/extensions/archive/master.zip
Everyone should already have an unzip program.

**Comment by uecasm** [comment]
How about this?

(The git process was the one that I've been using... it does make it a little easier to keep up-to-date, but you're right that it might scare off many people.)

**Comment by curiousdannii** [comment]
Thanks!

**Comment by uecasm** [comment]
I guess an open question is whether we should just import all the current public library extensions to here as well, to skip that step.  Then this would truly become an all-in-one replacement for the PL (sans thematic categorisation and IDE integration).

There's only two "blue" extensions (where the PL has a higher version number than what's here) and as far as I can tell the ones here are better anyway.

**Comment by curiousdannii** [comment]
Yeah we probably should. By all means go ahead if you feel so inclined. I'm sure many people would appreciate it!

**Pull request merged**
