### PR TITLE
Title Page

### PR DESCRIPTION
**Pull request by uecasm**
Bugfix for a Public Library extension, plus a new extension of my own that I made yesterday. 😁

### CODE REVIEW

**Comment by uecasm** [comment]
Out of curiosity, what's the status of this vs. the Public Library (the one still in the IDEs)?  Is there anyone still maintaining the PL?

I've noticed for example that the PL has `Menus by Wade Clarke (Version 5)`, while this has `Menus by Wade Clarke (Version 2/141228)`, and they both appear to be up to date with 6M62 but at different times and appear to be quite different from each other.

**Comment by juhana** [comment]
I think you should add a short note to the Ingold extension description about what's changed in version 4, the same way it documents changes in version 3.

**Comment by curiousdannii** [comment]
Inform making the date part of version numbers optional does make tracking updates difficult, so I highly recommend you add them to yours and any updates to other extensions.

I'm not sure to what extent the public library is being updated, though I assume Jon's extensions aren't as he doesn't use I7 anymore.

**Comment by uecasm** [comment]
I'm not sure the dates help all that much, since (at least as I read the docs; I didn't verify it) version 4/N will still win over version 3/M, regardless of what values N and M have.

But I added them anyway.

**Comment by curiousdannii** [comment]
> I'm not sure the dates help all that much, since (at least as I read the docs; I didn't verify it) version 4/N will still win over version 3/M, regardless of what values N and M have.

You're right, but that doesn't make them not useful. You were noting how there was version 2 and 5 of Wade's Menus. If both had dates it would let you know if version 2 had continued being developed in a distinct branch from 5, or if it was strictly an older past version.

**Comment by uecasm** [comment]
> > I'm not sure the dates help all that much, since (at least as I read the docs; I didn't verify it) version 4/N will still win over version 3/M, regardless of what values N and M have.
> 
> You're right, but that doesn't make them not useful. You were noting how there was version 2 and 5 of Wade's Menus. If both had dates it would let you know if version 2 had continued being developed in a distinct branch from 5, or if it was strictly an older past version.

I can tell it's a distinct branch, as I said.  They include changelog comments from different people updating it to different compiler versions out of step with each other.  FWIW I concluded that the one in the PL is probably the most recent, which also agrees with its higher version number.

**Pull request merged**
