### PR TITLE
Adding Inclusive Gender Options for 10.1

### PR DESCRIPTION
**Pull request by rileypb**

### CODE REVIEW

**Comment by neroden** [comment]
Phil -- I like it.  Two things:
- I think the "singular-they" gender should simply be called "singular-they" or something like that.  I'm uncomfortable using "non-conforming" for this.
- I'm completely willing to make this an update to my Gender Options extension.  It's all stuff I would have done if I'd managed to get it tested and working.

**Comment by rileypb** [comment]
Hi Nathanael, I tried to contact you a few months ago about this extension when I had added a fourth gender type and wanted to work on singular they. Zed Lopez contributed some code to make that work.

As to your points:
1. Sounds reasonable, renamed.
2. If you'd like to make this a new version of Gender Options by Nathanael Nerode, that's perfectly fine with me. I'll post a diff somewhere.
3. Added - let me know if it's sufficient.
4. Tests are updated, one test scenario has been added. I've added singular-they examples alongside the male/female/neuter examples. The new scenario tests third person story viewpoint.

**Comment by rileypb** [comment]
I just sent you the diff via PM on IntFiction.com.

**Comment by rileypb** [comment]
With regards to other pronouns, it can produce the correct text, but it can't recognize them of course, so I've left my test using zie/hir commented out.

**Comment by neroden** [comment]
I like it, the latest version looks great.

I'm sorry you had trouble reaching me.   I don't check the IntFiction forums much.  And frankly, I've been completely swamped with high-priority real-world stuff, mostly Covid safety  -- doctors's offices are routinely infecting people, including my partner, with Covid, because the doctor's aren't using the right respirator masks or air filters.  It has to stop.

My email for FLOSS projects is ncn_floss10 AT fastmail DOT fm , if you want to contact me in the future.  I will try to log in to IntFiction review the diff ASAP but I am very, very busy right now, and I might not get to it for a couple of weeks.

**Pull request closed without merging**
